# Rješavanje nelinearnih jednadžbi

##  Metoda bisekcije

In [62]:
from math import log,ceil

def funkcija(x):
    return x**2-2.0

def bisekcija(f,a,b,zamijeni=1,tol=1.0e-10):
    fa = f(a)
    if fa == 0.0: 
        return a
    fb = f(b)
    if fb == 0.0: 
        return b
    if fa*fb > 0.0: 
        print("Ne vrijedi f(a)f(b)<0")
        return
    n = ceil(log(abs(b - a)/tol)/log(2.0))
    print("n=",n)
    for i in range(n):
        c = 0.5*(a + b); fc = f(c)
        if (zamijeni == 1) and (abs(fc) > abs(fa)) \
                         and (abs(fc) > abs(fb)):
            return None
        if fc == 0.0: 
            return c
        if fb*fc < 0.0: 
            a = c; fa = fc
        else: 
            b = c; fb = fc
    return (a + b)/2.0

In [59]:
bisekcija(funkcija, 0,2)

n= 35


1.414213562355144

## Metoda jednostavnih iteracija

Potražimo nultočku jednadžbe $x^2-3x+1$

In [63]:
import matplotlib.pyplot as plt
import numpy as np
def varphi1(x):
    return (x*x+1)/3.0

def varphi2(x):
    return 3.0-1.0/x


def MJI(f, x0, Maxiter=15, tol=1.0e-10):
    n=0
    x = x0
    while abs(x - f(x)) > eps:
            print(n,x)
            x = f(x)
            n =n+1
            if(n > Maxiter): 
                print("n>MaxIter")
                break
    return x

In [61]:
eps = 10e-8
MJI(varphi1, 1,15)
MJI(varphi1, 2,15)
MJI(varphi1, 3,15)

0 1
1 0.6666666666666666
2 0.48148148148148145
3 0.41060813900320076
4 0.389533014605224
5 0.3839119898224779
6 0.3824628053098181
7 0.3820925991484853
8 0.3819982514413483
9 0.3819742213680825
10 0.38196810192991765
11 0.381966543630648
12 0.3819661468177146
0 2
1 1.6666666666666667
2 1.2592592592592593
3 0.8619112940100595
4 0.5809636929140317
5 0.4458396041614365
6 0.39959098421294215
7 0.3865576515547559
8 0.38314227265850936
9 0.38226600036597586
10 0.3820424316786
11 0.38198547320096593
12 0.381970967245522
13 0.38196727327282654
14 0.3819663326171594
0 3
1 3.3333333333333335
2 4.037037037037037
3 5.76588934613626
4 11.41515998396254
5 43.768625819819896
6 638.8975353851349
7 136063.68690706659
8 6171108965.248081
9 1.2694195286988415e+19
10 5.371419799473296e+37
11 9.617383554057915e+74
12 3.083135547528788e+149
13 3.1685749348118803e+298


inf

In [48]:
eps = 10e-10
MJI(varphi2,2,15)
MJI(varphi2,3,15)

0 2
1 2.5
2 2.6
3 2.6153846153846154
4 2.6176470588235294
5 2.6179775280898876
6 2.6180257510729614
7 2.6180327868852458
8 2.618033813400125
9 2.6180339631667064
10 2.618033985017358
0 3
1 2.6666666666666665
2 2.625
3 2.619047619047619
4 2.618181818181818
5 2.6180555555555554
6 2.618037135278515
7 2.6180344478216817
8 2.6180340557275543
9 2.6180339985218035
10 2.618033990175597


2.618033988957902

In [51]:
eps = 10e-8
def varphi1(x):
    return np.exp(-x)

def varphi2(x):
    return (1+x)/(1+np.exp(x))

def varphi3(x):
    return x+1-x*np.exp(x)
MJI(varphi1,0.5,15)
MJI(varphi2,0.5,15)
MJI(varphi3,0.5,15)

0 0.5
1 0.6065306597126334
2 0.545239211892605
3 0.5797030948780683
4 0.5600646279389019
5 0.5711721489772151
6 0.5648629469803235
7 0.5684380475700662
8 0.5664094527469208
9 0.5675596342622424
10 0.5669072129354714
11 0.5672771959707785
12 0.5670673518537281
13 0.5671863600876381
14 0.5671188642569858
15 0.5671571437076446
n>MaxIter
0 0.5
1 0.5663110031972182
2 0.5671431650348622
0 0.5
1 0.6756393646499359
2 0.3478126785112021
3 0.8553214091741074
4 -0.15650595538316914
5 0.9773264227477186
6 -0.6197642518955804
7 0.7137130874161464
8 0.256626649129847
9 0.9249206769105486
10 -0.40742240554225306
11 0.8636614202075393
12 -0.1847958494743267
13 0.9688201302439478
14 -0.5838599569295302
15 0.7417828828779736
n>MaxIter


0.1842794222830968

In [152]:
import numpy as np
import math
import matplotlib.pyplot as plt

def funkcija(x):
    return x*x-2

def derivacija(x):
    return 2*x

def Newton(f, df, x_0, tol=1.0e-10,x_star=1.0):
    x_old =x_0
    eps = 1.e-10
    BrIter = 1
    x_new = (x_old - f(x_old)/df(x_old))
    print("x" + str(BrIter) + " =", x_new)
    x=np.array([x_0])
    e=np.array([abs(x_0-x_star)])
    x=np.append(x,x_new)
    e=np.append(e,abs(x_new-x_star))
    while(abs(x_new - x_old) > eps * abs(x_0)):
        x_old = x_new
        x_new = (x_old - f(x_old)/df(x_old))
        BrIter+=1
        print("x" + str(BrIter) + " =", x_new)
        x=np.append(x,x_new)
        e=np.append(e,abs(x_new-x_star))
    return x_new, x, e



In [153]:
def funkcija(x):
    return x*x-2

def derivacija(x):
    return 2*x

Newton(funkcija, derivacija,2, tol=1.0e-10, x_star=np.sqrt(2))

x1 = 1.5
x2 = 1.4166666666666667
x3 = 1.4142156862745099
x4 = 1.4142135623746899
x5 = 1.4142135623730951


(1.4142135623730951,
 array([2.        , 1.5       , 1.41666667, 1.41421569, 1.41421356,
        1.41421356]),
 array([5.85786438e-01, 8.57864376e-02, 2.45310429e-03, 2.12390141e-06,
        1.59472435e-12, 0.00000000e+00]))

In [140]:
from scipy.optimize import root_scalar
y = root_scalar(funkcija, x0=2, fprime=derivacija, method='newton')

In [141]:
y

      converged: True
           flag: 'converged'
 function_calls: 10
     iterations: 5
           root: 1.4142135623730951

In [176]:
def funkcija2(x):
    return x**6-x-1

def derivacija2(x):
    return 6*x**5-1

Newton(funkcija2, derivacija2,0.5)

Newton(funkcija2, derivacija2,2)

x1 = -1.3269230769230769
x2 = -1.1016508087024928
x3 = -0.9256764026033771
x4 = -0.8164153166225413
x5 = -0.7809851583063968
x6 = -0.7781065698687246
x7 = -0.7780895992626766
x8 = -0.7780895986786011
x9 = -0.7780895986786011
x1 = 1.6806282722513088
x2 = 1.4307389882390624
x3 = 1.2549709561094364
x4 = 1.1615384327733131
x5 = 1.1363532741705054
x6 = 1.134730528343629
x7 = 1.1347241385002211
x8 = 1.1347241384015194


(1.1347241384015194,
 array([2.        , 1.68062827, 1.43073899, 1.25497096, 1.16153843,
        1.13635327, 1.13473053, 1.13472414, 1.13472414]),
 array([1.        , 0.68062827, 0.43073899, 0.25497096, 0.16153843,
        0.13635327, 0.13473053, 0.13472414, 0.13472414]))

x1 = -1.3269230769230769
x2 = -1.1016508087024928
x3 = -0.9256764026033771
x4 = -0.8164153166225413
x5 = -0.7809851583063968
x6 = -0.7781065698687246
x7 = -0.7780895992626766
x8 = -0.7780895986786011
x9 = -0.7780895986786011


(-0.7780895986786011,
 array([ 0.5       , -1.32692308, -1.10165081, -0.9256764 , -0.81641532,
        -0.78098516, -0.77810657, -0.7780896 , -0.7780896 , -0.7780896 ]),
 array([0.5       , 2.32692308, 2.10165081, 1.9256764 , 1.81641532,
        1.78098516, 1.77810657, 1.7780896 , 1.7780896 , 1.7780896 ]))

In [155]:
Newton(funkcija2, derivacija2,2)

x1 = 1.6806282722513088
x2 = 1.4307389882390624
x3 = 1.2549709561094364
x4 = 1.1615384327733131
x5 = 1.1363532741705054
x6 = 1.134730528343629
x7 = 1.1347241385002211
x8 = 1.1347241384015194


(1.1347241384015194,
 array([2.        , 1.68062827, 1.43073899, 1.25497096, 1.16153843,
        1.13635327, 1.13473053, 1.13472414, 1.13472414]),
 array([1.        , 0.68062827, 0.43073899, 0.25497096, 0.16153843,
        0.13635327, 0.13473053, 0.13472414, 0.13472414]))

In [175]:
coeff = np.array([1, 0, 0, 0, 0, -1, -1])
a=np.roots(coeff)
for i in range(len(a)):
    print(a[i])

(1.1347241384015188+0j)
(0.45105515860885603+1.0023645715871652j)
(0.45105515860885603-1.0023645715871652j)
(-0.6293724284703157+0.7357559529997771j)
(-0.6293724284703157-0.7357559529997771j)
(-0.7780895986786007+0j)


In [177]:
def funkcija3(x):
    return np.arctan(x)

def derivacija3(x):
    return 1/(1+x**2)
Newton(funkcija3, derivacija3,1.0, tol=1.e-16)
Newton(funkcija3, derivacija3,1.5, tol=1.e-16)

x1 = -0.5707963267948966
x2 = 0.1168599039989131
x3 = -0.001061022117044716
x4 = 7.963096044106416e-10
x5 = 0.0
x6 = 0.0
x1 = -1.6940796005538195
x2 = 2.321126961438388
x3 = -5.1140878367775136
x4 = 32.29568391421002
x5 = -1575.3169508212043
x6 = 3894976.0077608842
x7 = -23830288973552.125
x8 = 8.920280161123818e+26
x9 = -1.2499045993657107e+54
x10 = 2.4539946374984955e+108
x11 = -9.459476350342202e+216
x12 = inf
x13 = nan


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in double_scalars
  """
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: RuntimeWarning: divide by zero encountered in double_scalars
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: RuntimeWarning: invalid value encountered in double_scalars


(nan, array([ 1.50000000e+000, -1.69407960e+000,  2.32112696e+000,
        -5.11408784e+000,  3.22956839e+001, -1.57531695e+003,
         3.89497601e+006, -2.38302890e+013,  8.92028016e+026,
        -1.24990460e+054,  2.45399464e+108, -9.45947635e+216,
                     inf,              nan]), array([5.00000000e-001, 2.69407960e+000, 1.32112696e+000, 6.11408784e+000,
        3.12956839e+001, 1.57631695e+003, 3.89497501e+006, 2.38302890e+013,
        8.92028016e+026, 1.24990460e+054, 2.45399464e+108, 9.45947635e+216,
                    inf,             nan]))

In [156]:
Newton(funkcija3, derivacija3,1.0, tol=1.e-16)

x1 = -0.5707963267948966
x2 = 0.1168599039989131
x3 = -0.001061022117044716
x4 = 7.963096044106416e-10
x5 = 0.0
x6 = 0.0


(0.0,
 array([ 1.00000000e+00, -5.70796327e-01,  1.16859904e-01, -1.06102212e-03,
         7.96309604e-10,  0.00000000e+00,  0.00000000e+00]),
 array([0.        , 1.57079633, 0.8831401 , 1.00106102, 1.        ,
        1.        , 1.        ]))

In [151]:
newt(funkcija3, derivacija3,1.5, tol=1.e-16)

x1 = -1.6940796005538195
x2 = 2.321126961438388
x3 = -5.1140878367775136
x4 = 32.29568391421002
x5 = -1575.3169508212043
x6 = 3894976.0077608842
x7 = -23830288973552.125
x8 = 8.920280161123818e+26
x9 = -1.2499045993657107e+54
x10 = 2.4539946374984955e+108
x11 = -9.459476350342202e+216
x12 = inf
x13 = nan


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in double_scalars
  """
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: RuntimeWarning: divide by zero encountered in double_scalars
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: RuntimeWarning: invalid value encountered in double_scalars


(nan, array([ 1.50000000e+000, -1.69407960e+000,  2.32112696e+000,
        -5.11408784e+000,  3.22956839e+001, -1.57531695e+003,
         3.89497601e+006, -2.38302890e+013,  8.92028016e+026,
        -1.24990460e+054,  2.45399464e+108, -9.45947635e+216,
                     inf,              nan]), array([5.00000000e-001, 2.69407960e+000, 1.32112696e+000, 6.11408784e+000,
        3.12956839e+001, 1.57631695e+003, 3.89497501e+006, 2.38302890e+013,
        8.92028016e+026, 1.24990460e+054, 2.45399464e+108, 9.45947635e+216,
                    inf,             nan]))

# Newtonova metoda s promijenjenim korakom

In [174]:
BrIterMax = 50;
x_0 = 10.0;
f_old = np.abs(np.arctan(x_0))
eps = 1.e-10
x_prev = x_0

for BrIter in range(1,BrIterMax+1):
    s = -(1+x_prev**2)*np.arctan(x_prev)
    x = x_prev + s
    f_new = np.abs(np.arctan(x))
    alpha = 1.0
    while(f_old <= f_new):
        alpha=alpha/2
        x = x_prev + alpha*s
        f_new = np.abs(np.arctan(x))
    print("Iter=", BrIter, "x=",x, "alpha=", alpha)
    BrIter = BrIter+1
    f_old = f_new
    if(abs(x-x_prev) < eps*abs(x_0)):
        break;
    x_prev=x


Iter= 1 x= -8.57298688808465 alpha= 0.125
Iter= 2 x= 4.972971445878592 alpha= 0.125
Iter= 3 x= -3.854859757676751 alpha= 0.25
Iter= 4 x= 1.3669409069874696 alpha= 0.25
Iter= 5 x= -1.3271838200471255 alpha= 1.0
Iter= 6 x= 1.2273334774823526 alpha= 1.0
Iter= 7 x= -0.9960755661712501 alpha= 1.0
Iter= 8 x= 0.564651627108276 alpha= 1.0
Iter= 9 x= -0.11325732204034156 alpha= 1.0
Iter= 10 x= 0.0009660466837660697 alpha= 1.0
Iter= 11 x= -6.01039482506921e-10 alpha= 1.0
Iter= 12 x= 0.0 alpha= 1.0
