# 1. Faktorizacija Choleskog

Implementacija funkcije koja računa faktorizaciju Choleskog za simetričnu pozitivno definitnu matricu:

In [23]:
import numpy as np
from numpy import dot
from math import sqrt

def cholesky(A):
    n = len(A)
    for k in range(n):
        A[k,k] = sqrt(A[k,k] - dot(A[k,0:k],A[k,0:k]))
        for i in range(k+1,n):
            A[i,k] = (A[i,k] - dot(A[i,0:k],A[k,0:k]))/A[k,k]
    for k in range(1,n): A[0:k,k] = 0.0
    return A

Funkciju ćemo primijeniti na matrici $$\begin{bmatrix} 1& 2& 1\\ 2& 5& 2\\ 1& 2& 10\end{bmatrix}$$
Kao izlaz dobivamo matricu čiji gornji trokut je matrica $U$ a elementi ispod glavne dijagonale su elementi matrice $L$

In [24]:
A=np.array([[1.0, 2.0, 1.0 ],[2.0, 5.0, 2.0], [1.0, 2.0, 10.0]])
cholesky(A)
print("A=",A)



A= [[1. 0. 0.]
 [2. 1. 0.]
 [1. 0. 3.]]


# Dobivanje PLU faktorizacije pomoću Pythonove biblioteke NumPy i SciPy


lu funkcija iz scipy.linalg paketa kao izlaz daje matrice $P$, $L$, $U$, tako da je $A=PLU$, dakle matrica $P$ koju daje ova funkcija je zapravo transponirana matrica $P$ koju smo uveli na predavanjima, jer nam je dobro poznato $P^TP=I$. Dakle imamo: 
$P^T A=LU$


In [43]:
from scipy.linalg import lu

In [38]:
A=np.array([[3.0, 17.0, 10.0 ],[2.0, 4.0, -2.0], [6.0, 18.0, -12.0]])

In [39]:
P, L, U = lu(A)

In [45]:
print("P=\n", P)
print("L=\n", L)
print("U=\n", U)

P=
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L=
 [[ 1.          0.          0.        ]
 [ 0.5         1.          0.        ]
 [ 0.33333333 -0.25        1.        ]]
U=
 [[  6.  18. -12.]
 [  0.   8.  16.]
 [  0.   0.   6.]]


In [46]:
print("Permutacijska matrica=\n",np.transpose(P))

Permutacijska matrica=
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
